### PR TITLE
Fix extension rejecting valid auth tickets

### LINKED ISSUE #19: [Any/all] No detours getting hit + OnClientPreConnectEx not firing
After the new TF2 update, this extension causes an error in the console:
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils 004 before SteamAPI_Init succeeded.

The server continues to work, but when connecting, the error "Steam validation rejected" appears

### PR DESCRIPTION
**Pull request by Kenzzer**
- Fixes #19
- Fixes an unreported bug, where older version of the extension would reject steam tickets due to old gamedata
- Fixes the extension causing the srcds to reject valid auth tickets, due to begining the auth session too early

### CODE REVIEW

**Comment by asherkin** [comment]
So historically this was handled by `g_bSuppressCheckChallengeType` and not calling the engine's `CheckChallengeType` function (which is what then called `BeginAuthSession`, and why we handle `SetSteamID` ourselves as it was the only other important thing done in there) - seems like we should only have one of the two methods in play.

If going this route however, is there a reason to allow the call and supress the failure return, rather than blocking the call with a pre-hook?

**Comment by Kenzzer** [comment]
> If going this route however, is there a reason to allow the call and supress the failure return, rather than blocking the call with a pre-hook?

No particular intent, I wanted to avoid a pre hook and only use the post, since it's necessary to know whether the original auth session was valid, but it could be reworked to only require a pre hook.

**Comment by sapphonie** [comment]
Documented from discord discussion:
>>> 
- gamedata change, simple. Engine updated their steamgameserver interface version from 12 to 15, so that means virtual functions are not in the same place. TF2 now gets its own little section in the gamedata to reflect that
- the change from the extension's own CDetour to SM's CDetour has caused that `DETOUR_CREATE_MEMBER` no longer enables the detour by default. We need to do it ourselves
- finally when those two issues were fixed, the tf2 server (not connect this time) would kick the client, because connect already begun the auth session. So I sourcehooked into `ISteamGameServer::BeginAuthSession` to override the return `k_EBeginAuthSessionResultDuplicateRequest` to `k_EBeginAuthSessionResultOK` if and only connect was the one to initiate the auth session

**Comment by asherkin** [comment]
> No particular intent, I wanted to avoid a pre hook and only use the post, since it's necessary to know whether the original auth session was valid, but it could be reworked to only require a pre hook.

My main concern in this area is that the presence of Connect shouldn't be externally visible - passing auth tickets to Steam for validation twice is very visible, we don't want it to look like innocent players are involved in ticket reuse attempts. 

> I'll try to rework this, and account for `g_bSuppressCheckChallengeType` and perhaps fully replace it ?

I'm not precious about the original implementation, whatever works best - but we shouldn't have what seems to be a dead path / detour left around.

**Comment by sapphonie** [comment]
LGTM

**Comment by sapphonie** [comment]
This shouldn't break other branches, but it might, if so, cross that bridge etc etc

**Pull request merged**
